const memberinfo = [
  {
    id: 1,
    img: 'https://source.unsplash.com/random/300x300',
    name: 'Modar Soos',
    position: 'Programmer',
    phone: '+491231234567',
    email: 'modarsoos@gmail.com',
    website: 'https://www.modarsoos.com',
  },
  {
    id: 2,
    img: 'https://source.unsplash.com/random/199x300',
    name: 'Odai Sous',
    position: 'Son',
    phone: '+491239876543',
    email: 'odai@gmail.com',
    website: 'https://www.modarsoos.com',
  },
  {
    id: 3,
    img: 'https://source.unsplash.com/random/200x300',
    name: 'Bana Sous',
    position: 'Daughter',
    phone: '+491245678901',
    email: 'banasoos@gmail.com',
    website: 'https://www.modarsoos.com',
  },
  // Add more entries for a total of 10
  {
    id: 4,
    img: 'https://source.unsplash.com/random/250x250',
    name: 'John Doe',
    position: 'Designer',
    phone: '+49123456789',
    email: 'john.doe@gmail.com',
    website: 'https://www.johndoe.com',
  },
  {
    id: 5,
    img: 'https://source.unsplash.com/random/350x350',
    name: 'Alice Smith',
    position: 'Developer',
    phone: '+49123456789',
    email: 'alice.smith@gmail.com',
    website: 'https://www.alicesmith.com',
  },
  {
    id: 6,
    img: 'https://source.unsplash.com/random/275x275',
    name: 'Bob Johnson',
    position: 'Manager',
    phone: '+49123456789',
    email: 'bob.johnson@gmail.com',
    website: 'https://www.bobjohnson.com',
  },
  {
    id: 7,
    img: 'https://source.unsplash.com/random/320x320',
    name: 'Eva Davis',
    position: 'Tester',
    phone: '+49123456789',
    email: 'eva.davis@gmail.com',
    website: 'https://www.evadavis.com',
  },
  {
    id: 8,
    img: 'https://source.unsplash.com/random/400x400',
    name: 'Michael Brown',
    position: 'Analyst',
    phone: '+49123456789',
    email: 'michael.brown@gmail.com',
    website: 'https://www.michaelbrown.com',
  },
  {
    id: 9,
    img: 'https://source.unsplash.com/random/180x180',
    name: 'Sophia White',
    position: 'Architect',
    phone: '+49123456789',
    email: 'sophia.white@gmail.com',
    website: 'https://www.sophiawhite.com',
  },
  {
    id: 10,
    img: 'https://source.unsplash.com/random/280x280',
    name: 'David Lee',
    position: 'Consultant',
    phone: '+49123456789',
    email: 'david.lee@gmail.com',
    website: 'https://www.davidlee.com',
  },
  {
    id: 11,
    img: 'https://source.unsplash.com/random/320x220',
    name: 'Sarah Johnson',
    position: 'Marketing Specialist',
    phone: '+49123456789',
    email: 'sarah.johnson@gmail.com',
    website: 'https://www.sarahjohnson.com',
  },
  {
    id: 12,
    img: 'https://source.unsplash.com/random/280x180',
    name: 'Alex Turner',
    position: 'Sales Representative',
    phone: '+49123456789',
    email: 'alex.turner@gmail.com',
    website: 'https://www.alexturner.com',
  },
];

export default memberinfo;
